######################## default configuration ####################
baseURL = "/"
title = "welcome to yummy pizza website"
# theme = ""
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "#" # get your shortname form here : https://disqus.com

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/css/open-iconic-bootstrap.min.css" 
[[params.plugins.css]]
link = "plugins/css/animate.css" 
[[params.plugins.css]]
link = "plugins/css/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/css/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/css/aos.css" 
[[params.plugins.css]]
link = "plugins/css/ionicons.min.css" 
[[params.plugins.css]]
link = "plugins/css/bootstrap-datepicker.css"
[[params.plugins.css]]
link = "plugins/css/jquery.timepicker.css"
[[params.plugins.css]]
link = "plugins/css/flaticon.css"
[[params.plugins.css]]
link = "plugins/css/icomoon.css"
[[params.plugins.css]]
link = "plugins/css/style.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/js/jquery.min.js"
[[params.plugins.js]]
link = "plugins/js/jquery-migrate-3.0.1.min.js"
[[params.plugins.js]]
link = "plugins/js/popper.min.js"
[[params.plugins.js]]
link = "plugins/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/js/jquery.easing.1.3.js"
[[params.plugins.js]]
link = "plugins/js/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/js/jquery.stellar.min.js" 
[[params.plugins.js]]
link = "plugins/js/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/js/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/js/aos.js"
[[params.plugins.js]]
link = "plugins/js/jquery.animateNumber.min.js"
[[params.plugins.js]]
link = "plugins/js/bootstrap-datepicker.js"
[[params.plugins.js]]
link = "plugins/js/jquery.timepicker.min.js"
[[params.plugins.js]]
link = "plugins/js/scrollax.min.js"
[[params.plugins.js]]
link = "plugins/js/google-map.js"
[[params.plugins.js]]
link = "plugins/js/main.js"


#################### default parameters ################################
[params]
logo = "/images/logo.png"
# Meta data
description = "This is meta description"
author = ""
# copyright
copyright = "Copyright ©2022 All rights reserved"
designdevelop = "Designed & Developed by : [atcults](https://atcults.com/)"
address = ""
clock = ""
phone = ""
facebook = ""
tollfree = ""
sms = ""
Whatsapp = ""
email = ""

# ################################### English language #####################################
# [Languages.en]
# languageName = "En"
# languageCode = "en-us"
# contentDir = "content/english"
# weight = 1
# # copyright
# copyright = "Copyright ©2022 All rights reserved"
# browserviews = "This website is best viewed on IE 11+, Mozilla Firefox, Google"


